package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/yosefalemu/go-graphql.git/graph/model"
)

// CreateMovie is the resolver for the createMovie field.
func (r *mutationResolver) CreateMovie(ctx context.Context, input model.NewMovie) (*model.Movie, error) {
	movie := &model.Movie{
		Title: input.Title,
		URL:   input.URL,
	}
	//i want to return the movie that was created
	err := r.DB.Create(&movie).Error
	if err != nil {
		return nil, fmt.Errorf("error creating movie: %v", err)
	}

	return movie, nil
}

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context) ([]*model.Movie, error) {
	var movies []*model.Movie

	// Ensure you're passing only the context and not extra attached values
	err := r.DB.Find(&movies).Error
	if err != nil {
		return nil, fmt.Errorf("error fetching movies: %v", err)
	}

	return movies, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
