// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Actor struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type Movie struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	URL         string  `json:"url"`
	ReleaseDate *string `json:"releaseDate,omitempty"`
	CreatedAt   *string `json:"createdAt,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type NewActor struct {
	Name string `json:"name"`
}

type NewMovie struct {
	Title       string  `json:"title"`
	URL         string  `json:"url"`
	ReleaseDate *string `json:"releaseDate,omitempty"`
}

type Query struct {
}

type UpdateActor struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

type UpdateMovie struct {
	ID          string  `json:"id"`
	Title       *string `json:"title,omitempty"`
	URL         *string `json:"url,omitempty"`
	ReleaseDate *string `json:"releaseDate,omitempty"`
}
